#ifndef FFLI_SHAPE_TYPE_H_
#define FFLI_SHAPE_TYPE_H_

#include <nn/ffl/types.h>

enum FFLiShapeType
{
    FFLI_SHAPE_TYPE_OPA_BEARD       =  0,
    FFLI_SHAPE_TYPE_OPA_FACELINE    =  1,
    FFLI_SHAPE_TYPE_OPA_HAIR_1      =  2,
    FFLI_SHAPE_TYPE_OPA_FOREHEAD_1  =  3,
    FFLI_SHAPE_TYPE_XLU_MASK        =  4,
    FFLI_SHAPE_TYPE_XLU_NOSELINE    =  5,
    FFLI_SHAPE_TYPE_OPA_NOSE        =  6,
    FFLI_SHAPE_TYPE_OPA_CAP_1       =  7,
    FFLI_SHAPE_TYPE_XLU_GLASS       =  8,
    FFLI_SHAPE_TYPE_OPA_HAIR_2      =  9,
    FFLI_SHAPE_TYPE_OPA_FOREHEAD_2  = 10,
    FFLI_SHAPE_TYPE_OPA_CAP_2       = 11,
    FFLI_SHAPE_TYPE_MAX             = 12
};

#endif // FFLI_SHAPE_TYPE_H_
