#ifndef FFLI_TEXTURE_PARTS_TYPE_H_
#define FFLI_TEXTURE_PARTS_TYPE_H_

#include <nn/ffl/types.h>

enum FFLiTexturePartsType
{
    FFLI_TEXTURE_PARTS_TYPE_BEARD       =  0,
    FFLI_TEXTURE_PARTS_TYPE_CAP         =  1,
    FFLI_TEXTURE_PARTS_TYPE_EYE         =  2,
    FFLI_TEXTURE_PARTS_TYPE_EYEBROW     =  3,
    FFLI_TEXTURE_PARTS_TYPE_FACELINE    =  4,
    FFLI_TEXTURE_PARTS_TYPE_FACE_MAKEUP =  5,
    FFLI_TEXTURE_PARTS_TYPE_GLASS       =  6,
    FFLI_TEXTURE_PARTS_TYPE_MOLE        =  7,
    FFLI_TEXTURE_PARTS_TYPE_MOUTH       =  8,
    FFLI_TEXTURE_PARTS_TYPE_MUSTACHE    =  9,
    FFLI_TEXTURE_PARTS_TYPE_NOSELINE    = 10,
    FFLI_TEXTURE_PARTS_TYPE_MAX         = 11
};

#endif // FFLI_TEXTURE_PARTS_TYPE_H_
