#ifndef FFLI_SHAPE_PARTS_TYPE_H_
#define FFLI_SHAPE_PARTS_TYPE_H_

#include <nn/ffl/types.h>

enum FFLiShapePartsType
{
    FFLI_SHAPE_PARTS_TYPE_BEARD         =  0,
    FFLI_SHAPE_PARTS_TYPE_CAP_1         =  1,
    FFLI_SHAPE_PARTS_TYPE_CAP_2         =  2,
    FFLI_SHAPE_PARTS_TYPE_FACELINE      =  3,
    FFLI_SHAPE_PARTS_TYPE_GLASS         =  4,
    FFLI_SHAPE_PARTS_TYPE_MASK          =  5,
    FFLI_SHAPE_PARTS_TYPE_NOSELINE      =  6,
    FFLI_SHAPE_PARTS_TYPE_NOSE          =  7,
    FFLI_SHAPE_PARTS_TYPE_HAIR_1        =  8,
    FFLI_SHAPE_PARTS_TYPE_HAIR_2        =  9,
    FFLI_SHAPE_PARTS_TYPE_FOREHEAD_1    = 10,
    FFLI_SHAPE_PARTS_TYPE_FOREHEAD_2    = 11,
    FFLI_SHAPE_PARTS_TYPE_MAX           = 12
};

#endif // FFLI_SHAPE_PARTS_TYPE_H_
